name: Build Template
on: push

jobs:
    build-template:
        name: Build Mustache template
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Reset to HEAD
              run: git reset --hard HEAD

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9.2"

            - name: Install pipenv
              run: pip install pipenv

            - name: Install dependencies
              run: pipenv install

            - name: Render Mustache template
              run: pipenv run python3 build.py

            - name: Commit and push changes
              uses: actions-js/push@master
